# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    strategy:
      matrix:
        rid: [linux-x64]
        release: [Release]

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build ./source/SimpleConsole/SimpleConsole.csproj --self-contained --no-restore --runtime ${{ matrix.rid }} -c ${{ matrix.release }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish ./source/SimpleConsole/SimpleConsole.csproj --self-contained --no-build --runtime ${{ matrix.rid }} -c ${{ matrix.release }}
      
    - name: Zip Outputs
      uses: montudor/action-zip@v1
      with:
        args: zip --q -r SimpleConsole.${{ matrix.rid }}.zip ./source/SimpleConsole/bin/${{ matrix.release }}/net6.0/${{ matrix.rid }}/publish/
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'SimpleConsole.${{ matrix.rid }}.zip'
        path: './SimpleConsole.${{ matrix.rid }}.zip'